### ISSUE TITLE
Thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by rllola** [mimblewimble/grin-miner#15]
I am trying to run grin-miner on testnet to get testnet coin. I did a docker and started it using instruction from the doc.

I have this to start : 
```
ENTRYPOINT ["grin-miner"]
```

and I get this error:
```
$ docker run -it grin-miner 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by bladedoyle** [comment]
Please share the Dockerfile you used.
A few things to note:
* you need to start grin-miner from the same directory that contains the grin-miner.toml config file so that probably means setting "WORKDIR" in the dockerfile
* the miner has a TUI (Text-UI) enabled by default, so you can either disable that in the grin-miner.toml file, or else you need to in the Dockerfile:  `ENV LANG=C.UTF-8`

If that does not help, please share you Dockerfile, and the output with RUST_BACKTRACE=1 if you can.

**Comment by rllola** [comment]
Here my docker file : 
https://github.com/rllola/grin-miner/blob/dockerfile/Dockerfile

It is working now I was most likely missing the grin-miner.toml
I have the TUI but now it is a connection problem. It seems to not be able to find the grin server but I think it is a docker newtork issue.

The error information is not really helpful is there a way to show the proper error ?
